config/routes.rb
Stella::Application.routes.draw do
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :characters
end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?
  has_many :characters
  def set_default_role
    self.role ||= :user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # Able to see only the main page without the character
  before_action :have_character , except: [:index]
  
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "Access denied."
    redirect_to (request.referrer || root_path)
  end

  def have_character
    #debug current_user
    if user_signed_in?
      if action_name!='destroy'
        if controller_name!= 'characters' && controller_name!='devise/sessions'
          if current_user.characters.blank?
            #current_user.inspect
            redirect_to new_character_path
          end
        end
      end
    end
  end

end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
	before_action :set_character, only: [:show, :edit, :update, :destroy]


	def index
    	@characters = Character.all
  	end

  	def show
  	end

  	def new
  		@character = Character.new
  	end

  	def edit
  	end

	def create
		# @user = User.find_by_id(2)
		@user = current_user
		@character = @user.characters.create(character_params)
		redirect_to character_path(@character)
	end


	def update
		if @character.update(character_params)
			redirect_to @character, notice: 'Character was successfully updated.'
		else
			render action: 'edit'
		end
	end

	def destroy
		@character.destroy
		redirect_to characters_url
	end

	private

		def set_character
	      @character = Character.find(params[:id])
	    end


		def character_params
			params.require(:character).permit(:name,:surname)
			#params.require(:character).permit(current_user.name, :surname)
		end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized, except: [:show]

  def index
    @users = User.all
    authorize @users
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to root_path, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/index.html.erb
<div class="container">
  <div class="row">
    <h3>Characters</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @characters.each do |char| %>
            <tr>
              <td>
                <%= char.name %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/characters/new.html.erb
<%= simple_form_for @character do |f| %>
	<%= f.input :name %>
	<%= f.input :surname %>
	<%= f.button :submit %>
<% end %>

app/views/characters/show.html.erb
<h3>Character</h3>
<p>Email: <%= @character.user.email %></p>
<p>imie: <%= @character.name %></p>
<p>nazwisko: <%= @character.surname %></p>

app/views/home/index.html.erb
<h3>Home</h3>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Characters', characters_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Stella" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Stella" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
   
  </body>
</html>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>